# Use an official Node runtime as a parent image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies including 'devDependencies'
RUN npm install

# Install nodemon globally within the container
RUN npm install -g nodemon

# Copy the rest of your application's code
COPY . .

# Set environment variable to development
ENV NODE_ENV=development

# Expose port 3000 to the outside once the container is launched
EXPOSE 3000

# Run the application using nodemon
CMD ["nodemon", "--exec", "node", "src/index.js"]
