version: '3.8'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3366:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=chirper
      - MYSQL_DATABASE=chirper_local
      - MYSQL_PASSWORD=secret
      - ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./src/database/db.sql:/docker-entrypoint-initdb.d/db.sql

  # node:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MYSQL_HOST=mysql
  #     - MYSQL_PORT=3306
  #     - MYSQL_USER=chirper
  #     - MYSQL_PASSWORD=secret
  #     - MYSQL_DATABASE=chirper_local
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   depends_on:
  #     - mysql
